# docker-compose.yml
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=Backend/rest.py
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
